
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dymoo6791
 */
public class gameFrame extends javax.swing.JFrame {
    String userTotal, com2Card;
    int firstValUser, secValUser, thirdValUser,fourthValUser, userTotal2C, userTotal3C;
    int firstValCom, secValCom, thirdValCom,fourthValCom, comTotal2C, userBlackJack, comBlackJack;
    Random rand = new Random();
    String[] cards
            = new String[]{"2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"};


    public gameFrame() {
        initComponents();
        comCard2.setVisible(false);
        comCard3.setVisible(false);
        comCard4.setVisible(false);
        userCardLbl3.setVisible(false);
        userCardLbl4.setVisible(false);
        userCardLbl5.setVisible(false);
        userCardLbl1.setVisible(false);
        userCardLbl2.setVisible(false);
        comCard1.setVisible(false);
        com2Hidden.setVisible(false);
        hit2CardsBtn.setVisible(false);
        stand2CardsBtn.setVisible(false);
        hit3CardsBtn.setVisible(false);
        userTotalLbl.setVisible(false);
        comTotalLbl.setVisible(false);
        thirdHitLbl1.setVisible(false);
        thirdHitLbl2.setVisible(false);
        thirdHitLbl3.setVisible(false);
        thirdHitLbl4.setVisible(false);
        userCardLbl6.setVisible(false);
        userCardLbl7.setVisible(false);
        userCardLbl8.setVisible(false);
        userCardLbl9.setVisible(false);
        newGameBtn.setVisible(false);
        NoMoreLbl.setVisible(false);
        winOrLoseLbl.setVisible(false);
        comCardStorage2.setVisible(false);
        comCardStorage3.setVisible(false);
        comCardStorage4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userCardLbl6 = new javax.swing.JLabel();
        thirdHitLbl2 = new javax.swing.JLabel();
        thirdHitLbl3 = new javax.swing.JLabel();
        thirdHitLbl4 = new javax.swing.JLabel();
        thirdHitLbl1 = new javax.swing.JLabel();
        hit2CardsBtn = new javax.swing.JButton();
        stand2CardsBtn = new javax.swing.JButton();
        newGameBtn = new javax.swing.JButton();
        userCardLbl1 = new javax.swing.JLabel();
        userCardLbl2 = new javax.swing.JLabel();
        userCardLbl3 = new javax.swing.JLabel();
        StartBtn = new javax.swing.JButton();
        userCardLbl4 = new javax.swing.JLabel();
        userCardLbl5 = new javax.swing.JLabel();
        userTotalLbl = new javax.swing.JLabel();
        comCard3 = new javax.swing.JLabel();
        comCard2 = new javax.swing.JLabel();
        comCard1 = new javax.swing.JLabel();
        comCard4 = new javax.swing.JLabel();
        com2Hidden = new javax.swing.JLabel();
        dealerBustLbl = new javax.swing.JLabel();
        hit3CardsBtn = new javax.swing.JButton();
        comCardStorage2 = new javax.swing.JLabel();
        comCardStorage3 = new javax.swing.JLabel();
        comTotalLbl = new javax.swing.JLabel();
        comCardStorage4 = new javax.swing.JLabel();
        userCardLbl7 = new javax.swing.JLabel();
        userCardLbl8 = new javax.swing.JLabel();
        userCardLbl9 = new javax.swing.JLabel();
        NoMoreLbl = new javax.swing.JLabel();
        winOrLoseLbl = new javax.swing.JLabel();
        userBustLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userCardLbl6.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userCardLbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCardLbl6.setText("0");
        userCardLbl6.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userCardLbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 120, 170));

        thirdHitLbl2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(thirdHitLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 170));

        thirdHitLbl3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(thirdHitLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 120, 170));

        thirdHitLbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FNV lucky38.png"))); // NOI18N
        thirdHitLbl4.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(thirdHitLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 170));

        thirdHitLbl1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(thirdHitLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 170));

        hit2CardsBtn.setText("Hit ");
        hit2CardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hit2CardsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hit2CardsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 102, 36));

        stand2CardsBtn.setText("Stand ");
        stand2CardsBtn.setMaximumSize(new java.awt.Dimension(45, 23));
        stand2CardsBtn.setMinimumSize(new java.awt.Dimension(45, 23));
        stand2CardsBtn.setPreferredSize(new java.awt.Dimension(45, 23));
        stand2CardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stand2CardsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(stand2CardsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, 102, 36));

        newGameBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newGameBtn.setForeground(new java.awt.Color(255, 255, 255));
        newGameBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FNV lucky38.png"))); // NOI18N
        newGameBtn.setText("New Game");
        newGameBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newGameBtn.setOpaque(false);
        newGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameBtnActionPerformed(evt);
            }
        });
        jPanel1.add(newGameBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 130, 170));

        userCardLbl1.setBackground(new java.awt.Color(255, 255, 255));
        userCardLbl1.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userCardLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCardLbl1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userCardLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 120, 170));

        userCardLbl2.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userCardLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCardLbl2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userCardLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 120, 170));

        userCardLbl3.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userCardLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCardLbl3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userCardLbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 120, 170));

        StartBtn.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        StartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lucky38Deal.png"))); // NOI18N
        StartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtnActionPerformed(evt);
            }
        });
        jPanel1.add(StartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 120, 170));

        userCardLbl4.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userCardLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCardLbl4.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userCardLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 120, 170));

        userCardLbl5.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userCardLbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCardLbl5.setText("0");
        userCardLbl5.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userCardLbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 120, 170));

        userTotalLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userTotalLbl.setText("Total:");
        jPanel1.add(userTotalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 230, -1));

        comCard3.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        comCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FNV lucky38.png"))); // NOI18N
        comCard3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 120, 170));

        comCard2.setFont(new java.awt.Font("Lao UI", 0, 14)); // NOI18N
        comCard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comCard2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 120, 170));

        comCard1.setBackground(new java.awt.Color(255, 255, 255));
        comCard1.setFont(StartBtn.getFont());
        comCard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comCard1.setText("?");
        comCard1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 170));

        comCard4.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        comCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FNV lucky38.png"))); // NOI18N
        comCard4.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 120, 170));

        com2Hidden.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        com2Hidden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FNV lucky38.png"))); // NOI18N
        com2Hidden.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(com2Hidden, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 120, 170));

        dealerBustLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(dealerBustLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 410, 90));

        hit3CardsBtn.setText("Hit");
        hit3CardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hit3CardsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hit3CardsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 102, 36));
        jPanel1.add(comCardStorage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 70, 70));

        comCardStorage3.setText("0");
        jPanel1.add(comCardStorage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 60, 60));

        comTotalLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comTotalLbl.setText("Total:");
        jPanel1.add(comTotalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, -1));

        comCardStorage4.setText("0");
        jPanel1.add(comCardStorage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 60, 60));

        userCardLbl7.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userCardLbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCardLbl7.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userCardLbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 120, 170));

        userCardLbl8.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userCardLbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCardLbl8.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userCardLbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 120, 170));

        userCardLbl9.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userCardLbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCardLbl9.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userCardLbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 120, 170));

        NoMoreLbl.setText("You're only getting 4 cards");
        jPanel1.add(NoMoreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 140, 30));

        winOrLoseLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(winOrLoseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 410, 90));

        userBustLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(userBustLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 410, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hit2CardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hit2CardsBtnActionPerformed
        String Card1 = userCardLbl1.getText();
        String Card2 = userCardLbl2.getText();
        userCardLbl3.setText(Card1);
        userCardLbl4.setText(Card2);
        userHit();
        hit2CardsBtn.setVisible(false);
        userCardLbl3.setVisible(true);
        userCardLbl4.setVisible(true);
        userCardLbl5.setVisible(true);
        userCardLbl1.setVisible(false);
        userCardLbl2.setVisible(false);
    }//GEN-LAST:event_hit2CardsBtnActionPerformed

    private void stand2CardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stand2CardsBtnActionPerformed
        String userCard1 = userCardLbl1.getText();
        String userCard2 = userCardLbl2.getText();
        String userCard3 = userCardLbl5.getText();
        String userCard4 = userCardLbl6.getText();
        userTotalLbl.setText(userTotalCards(userCard1, userCard2, userCard3,userCard4));
        String com1 = comCard1.getText();
        String com2 = comCardStorage2.getText();
        String com3 = comCardStorage3.getText();
        String com4 = comCardStorage4.getText();
        comTotalLbl.setText(comTotal(com1, com2, com3, com4));
        String test = userTotalLbl.getText();
        String run = comTotalLbl.getText();
        winOrLose(test,run);
        newGameBtn.setVisible(true);
    }//GEN-LAST:event_stand2CardsBtnActionPerformed

    private void StartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtnActionPerformed
        userCards();
        comCards();
        
        userCardLbl1.setVisible(true);
        userCardLbl2.setVisible(true);
        comCard1.setVisible(true);
        com2Hidden.setVisible(true);
        hit2CardsBtn.setVisible(true);
        stand2CardsBtn.setVisible(true);
        hit3CardsBtn.setVisible(true);

        userTotalLbl.setVisible(true);
        comTotalLbl.setVisible(true);
       
        StartBtn.setVisible(false);
        userCardLbl3.setVisible(false);
        userCardLbl4.setVisible(false);
        userCardLbl5.setVisible(false);  
        if (comTotal2C < 13) {
            comHit();
            comCard1.setVisible(false);
            com2Hidden.setVisible(false);
            comCard2.setVisible(true);
            comCard3.setVisible(true);
            comCard4.setVisible(true);
        } else if (comTotal2C >21){
            dealerBustLbl.setText("Dealer Busted");
        }
    }//GEN-LAST:event_StartBtnActionPerformed

    private void hit3CardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hit3CardsBtnActionPerformed
        String Card1 = userCardLbl3.getText();
        String Card2 = userCardLbl4.getText();
        String Card3 = userCardLbl5.getText();
        userCardLbl7.setText(Card1);
        userCardLbl8.setText(Card2);
        userCardLbl9.setText(Card3);
        userHitAgain();
        NoMoreLbl.setVisible(true);
        hit3CardsBtn.setVisible(false);
        hit2CardsBtn.setVisible(false);
        userCardLbl3.setVisible(false);
        userCardLbl4.setVisible(false);
        userCardLbl5.setVisible(false);
        userCardLbl1.setVisible(false);
        userCardLbl2.setVisible(false);
        userCardLbl6.setVisible(true);
        userCardLbl7.setVisible(true);
        userCardLbl8.setVisible(true);
        userCardLbl9.setVisible(true);
    }//GEN-LAST:event_hit3CardsBtnActionPerformed

    private void newGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameBtnActionPerformed
         this.setVisible(false);
       new mainMenuFrame().setVisible(true);
    }//GEN-LAST:event_newGameBtnActionPerformed

    public void userCards() {
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            userCardLbl1.setText(cards[0]);
        }
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            userCardLbl2.setText(cards[0]);
        }
    }

    public void comCards() {
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            comCard1.setText(cards[0]);
        }
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            comCardStorage2.setText(cards[0]);
        }
    }

    public void userHit() {
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            userCardLbl5.setText(cards[0]);
        }
    }
    public void userHitAgain() {
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            userCardLbl6.setText(cards[0]);
        }
    }

    public void comHit() {
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            comCardStorage3.setText(cards[0]);
        }
        String comFirst = comCard1.getText();
        comCard2.setText(comFirst);
        comCard1.setVisible(true);
        com2Hidden.setVisible(true);
        comCard2.setVisible(false);
        comCard3.setVisible(false);
        comCard4.setVisible(false);
    }

    public String comTotal(String v1, String v2, String v3, String v4) {
        switch (v1) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                firstValCom = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                firstValCom = Integer.parseInt(convert);
                break;
            }
            default:
                firstValCom = Integer.parseInt(v1);
                break;
        }
        ////////////////////////////////////////////
        switch (v2) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                secValCom = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                secValCom = Integer.parseInt(convert);
                break;
            }
            default:
                secValCom = Integer.parseInt(v2);
                break;
        }   
        /////////////////////////////////////////////////////
        switch (v3) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                thirdValCom = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                thirdValCom = Integer.parseInt(convert);
                break;
            }
            default:
                thirdValCom = Integer.parseInt(v3);
                break;
        }        
        //////////////////////////////////////////////////////
        switch (v4) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                fourthValCom = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                fourthValCom = Integer.parseInt(convert);
                break;
            }
            default:
                fourthValCom = Integer.parseInt(v4);
                break;
        }
        comTotal2C = firstValCom + secValCom + thirdValCom + fourthValCom;
        comBlackJack = firstValCom + secValCom;
        
 if (comBlackJack == 21) {
            dealerBustLbl.setText("Dealer has BlackJack");
            StartBtn.setVisible(true);
        } else if (comTotal2C > 21) {
            dealerBustLbl.setText("Dealer Busted");
        }
        com2Card = Integer.toString(comTotal2C);
        return com2Card;
    }

    public String userTotalCards(String v1, String v2,String v3, String v4) {
        switch (v1) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                firstValUser = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                firstValUser = Integer.parseInt(convert);
                break;
            }
            default:
                firstValUser = Integer.parseInt(v1);
                break;
        }
        ////////////////////////////////////////////
        switch (v2) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                secValUser = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                secValUser = Integer.parseInt(convert);
                break;
            }
            default:
                secValUser = Integer.parseInt(v2);
                break;
        }
        ////////////////////////////////////////////
        switch (v3) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                thirdValUser = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                thirdValUser = Integer.parseInt(convert);
                break;
            }
            default:
                thirdValUser = Integer.parseInt(v3);
                break;
        }
        ////////////////////////////////////////////
        switch (v4) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                fourthValUser = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                fourthValUser = Integer.parseInt(convert);
                break;
            }
            default:
                fourthValUser = Integer.parseInt(v4);
                break;
        }
        userTotal2C = firstValUser + secValUser + thirdValUser + fourthValUser;
        userBlackJack = firstValUser + secValUser;
        if (userTotal2C > 21){
            userBustLbl.setText("Bust");
        } else if(userBlackJack == 21){
            userBustLbl.setText("BlackJack");
        }
        userTotal = Integer.toString(userTotal2C);
        return userTotal;
    }
    public void winOrLose(String v1, String v2){
        int uT = Integer.parseInt(v1); //User Total
        int cT = Integer.parseInt(v2); //Com Total
        if((uT > cT) && (uT < 22)){
            winOrLoseLbl.setVisible(true);
            winOrLoseLbl.setText("You Win");
        } else if((cT >= uT )&& (cT < 22)){
            winOrLoseLbl.setText("Dealer Wins");
            winOrLoseLbl.setVisible(true);
        }   
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NoMoreLbl;
    private javax.swing.JButton StartBtn;
    private javax.swing.JLabel com2Hidden;
    private javax.swing.JLabel comCard1;
    private javax.swing.JLabel comCard2;
    private javax.swing.JLabel comCard3;
    private javax.swing.JLabel comCard4;
    private javax.swing.JLabel comCardStorage2;
    private javax.swing.JLabel comCardStorage3;
    private javax.swing.JLabel comCardStorage4;
    private javax.swing.JLabel comTotalLbl;
    private javax.swing.JLabel dealerBustLbl;
    private javax.swing.JButton hit2CardsBtn;
    private javax.swing.JButton hit3CardsBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newGameBtn;
    private javax.swing.JButton stand2CardsBtn;
    private javax.swing.JLabel thirdHitLbl1;
    private javax.swing.JLabel thirdHitLbl2;
    private javax.swing.JLabel thirdHitLbl3;
    private javax.swing.JLabel thirdHitLbl4;
    private javax.swing.JLabel userBustLbl;
    private javax.swing.JLabel userCardLbl1;
    private javax.swing.JLabel userCardLbl2;
    private javax.swing.JLabel userCardLbl3;
    private javax.swing.JLabel userCardLbl4;
    private javax.swing.JLabel userCardLbl5;
    private javax.swing.JLabel userCardLbl6;
    private javax.swing.JLabel userCardLbl7;
    private javax.swing.JLabel userCardLbl8;
    private javax.swing.JLabel userCardLbl9;
    private javax.swing.JLabel userTotalLbl;
    private javax.swing.JLabel winOrLoseLbl;
    // End of variables declaration//GEN-END:variables
}
