
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dymoo6791
 */
public class gameFrame extends javax.swing.JFrame {

    String userTotal, com2Card;
    int firstValUser, secValUser, thirdValUser, fourthValUser, userTotal2C, userTotal3C;
    int firstValCom, secValCom, thirdValCom, fourthValCom, comTotal2C, userBlackJack, comBlackJack;
    Random rand = new Random();
    String[] cards = new String[]{"2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"}; //Card Selection

    public gameFrame() { //Hides all components on the panel on launch
        initComponents();
        comHand2Card1.setVisible(false);
        comHand2Card2.setVisible(false);
        comHand2Card3.setVisible(false);
        userHand2Card1.setVisible(false);
        userHand2Card2.setVisible(false);
        userHand2Card3.setVisible(false);
        userHand1Card1.setVisible(false);
        userHand1Card2.setVisible(false);
        comHand1Card1.setVisible(false);
        comHand1Card2.setVisible(false);
        hit2CardsBtn.setVisible(false);
        standBtn.setVisible(false);
        hit3CardsBtn.setVisible(false);
        userTotalLbl.setVisible(false);
        comTotalLbl.setVisible(false);
        comHand3Card1.setVisible(false);
        comHand3Card2.setVisible(false);
        comHand3Card3.setVisible(false);
        comHand3Card4.setVisible(false);
        userHand3Card4.setVisible(false);
        userHand3Card1.setVisible(false);
        userHand3Card2.setVisible(false);
        userHand3Card3.setVisible(false);
        newGameBtn.setVisible(false);
        NoMoreLbl.setVisible(false);
        winOrLoseLbl.setVisible(false);
        comCardStorage2.setVisible(false);
        comCardStorage3.setVisible(false);
        comCardStorage4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comHand3Card1 = new javax.swing.JLabel();
        comHand3Card2 = new javax.swing.JLabel();
        comHand3Card3 = new javax.swing.JLabel();
        comHand3Card4 = new javax.swing.JLabel();
        hit2CardsBtn = new javax.swing.JButton();
        standBtn = new javax.swing.JButton();
        newGameBtn = new javax.swing.JButton();
        StartBtn = new javax.swing.JButton();
        userHand1Card1 = new javax.swing.JLabel();
        userHand1Card2 = new javax.swing.JLabel();
        userHand2Card1 = new javax.swing.JLabel();
        userHand2Card2 = new javax.swing.JLabel();
        userHand2Card3 = new javax.swing.JLabel();
        userHand3Card1 = new javax.swing.JLabel();
        userHand3Card2 = new javax.swing.JLabel();
        userHand3Card3 = new javax.swing.JLabel();
        userHand3Card4 = new javax.swing.JLabel();
        userTotalLbl = new javax.swing.JLabel();
        comHand1Card1 = new javax.swing.JLabel();
        comHand2Card1 = new javax.swing.JLabel();
        comHand2Card2 = new javax.swing.JLabel();
        comHand2Card3 = new javax.swing.JLabel();
        comHand1Card2 = new javax.swing.JLabel();
        dealerBustLbl = new javax.swing.JLabel();
        hit3CardsBtn = new javax.swing.JButton();
        comCardStorage2 = new javax.swing.JLabel();
        comCardStorage3 = new javax.swing.JLabel();
        comCardStorage4 = new javax.swing.JLabel();
        comTotalLbl = new javax.swing.JLabel();
        NoMoreLbl = new javax.swing.JLabel();
        winOrLoseLbl = new javax.swing.JLabel();
        userBustLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comHand3Card1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comHand3Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 170));

        comHand3Card2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comHand3Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 170));

        comHand3Card3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comHand3Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 120, 170));

        comHand3Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FNV lucky38.png"))); // NOI18N
        comHand3Card4.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comHand3Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, 170));

        hit2CardsBtn.setText("Hit ");
        hit2CardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hit2CardsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hit2CardsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 102, 36));

        standBtn.setText("Stand ");
        standBtn.setMaximumSize(new java.awt.Dimension(45, 23));
        standBtn.setMinimumSize(new java.awt.Dimension(45, 23));
        standBtn.setPreferredSize(new java.awt.Dimension(45, 23));
        standBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standBtnActionPerformed(evt);
            }
        });
        jPanel1.add(standBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, 102, 36));

        newGameBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newGameBtn.setForeground(new java.awt.Color(255, 255, 255));
        newGameBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FNV lucky38.png"))); // NOI18N
        newGameBtn.setText("New Game");
        newGameBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newGameBtn.setOpaque(false);
        newGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameBtnActionPerformed(evt);
            }
        });
        jPanel1.add(newGameBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 130, 170));

        StartBtn.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        StartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lucky38Deal.png"))); // NOI18N
        StartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtnActionPerformed(evt);
            }
        });
        jPanel1.add(StartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 120, 170));

        userHand1Card1.setBackground(new java.awt.Color(255, 255, 255));
        userHand1Card1.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userHand1Card1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userHand1Card1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userHand1Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 120, 170));

        userHand1Card2.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userHand1Card2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userHand1Card2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userHand1Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 120, 170));

        userHand2Card1.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userHand2Card1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userHand2Card1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userHand2Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 120, 170));

        userHand2Card2.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userHand2Card2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userHand2Card2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userHand2Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 120, 170));

        userHand2Card3.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userHand2Card3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userHand2Card3.setText("0");
        userHand2Card3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userHand2Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 120, 170));

        userHand3Card1.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userHand3Card1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userHand3Card1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userHand3Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 120, 170));

        userHand3Card2.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userHand3Card2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userHand3Card2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userHand3Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 120, 170));

        userHand3Card3.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userHand3Card3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userHand3Card3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userHand3Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 120, 170));

        userHand3Card4.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        userHand3Card4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userHand3Card4.setText("0");
        userHand3Card4.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(userHand3Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 120, 170));

        userTotalLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userTotalLbl.setText("Total:");
        jPanel1.add(userTotalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 230, -1));

        comHand1Card1.setBackground(new java.awt.Color(255, 255, 255));
        comHand1Card1.setFont(StartBtn.getFont());
        comHand1Card1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comHand1Card1.setText("?");
        comHand1Card1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comHand1Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 170));

        comHand2Card1.setFont(new java.awt.Font("Lao UI", 0, 14)); // NOI18N
        comHand2Card1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comHand2Card1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comHand2Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 120, 170));

        comHand2Card2.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        comHand2Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FNV lucky38.png"))); // NOI18N
        comHand2Card2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comHand2Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 120, 170));

        comHand2Card3.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        comHand2Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FNV lucky38.png"))); // NOI18N
        comHand2Card3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comHand2Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 120, 170));

        comHand1Card2.setFont(new java.awt.Font("Lao UI", 0, 12)); // NOI18N
        comHand1Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FNV lucky38.png"))); // NOI18N
        comHand1Card2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.add(comHand1Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 120, 170));

        dealerBustLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(dealerBustLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 410, 90));

        hit3CardsBtn.setText("Hit");
        hit3CardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hit3CardsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hit3CardsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 102, 36));
        jPanel1.add(comCardStorage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 70, 70));

        comCardStorage3.setText("0");
        jPanel1.add(comCardStorage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 60, 60));

        comCardStorage4.setText("0");
        jPanel1.add(comCardStorage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 60, 60));

        comTotalLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comTotalLbl.setText("Total:");
        jPanel1.add(comTotalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, -1));

        NoMoreLbl.setText("You're only getting 4 cards");
        jPanel1.add(NoMoreLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 140, 30));

        winOrLoseLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(winOrLoseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 410, 90));

        userBustLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(userBustLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 410, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hit2CardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hit2CardsBtnActionPerformed
        String Card1 = userHand1Card1.getText(); //gets value from first 2 cards
        String Card2 = userHand1Card2.getText();
        userHand2Card1.setText(Card1); //moves first 2 values to next set of cards
        userHand2Card2.setText(Card2);
        userHit(); //calls to userHit Method to give user another card

        hit2CardsBtn.setVisible(false);//hides first hit button to prevent possible bugs
        userHand2Card1.setVisible(true);
        userHand2Card2.setVisible(true);
        userHand2Card3.setVisible(true); //add card and move to next set
        userHand1Card1.setVisible(false);
        userHand1Card2.setVisible(false);
    }//GEN-LAST:event_hit2CardsBtnActionPerformed

    private void standBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standBtnActionPerformed
        String userCard1 = userHand1Card1.getText();
        String userCard2 = userHand1Card2.getText(); //Get Values from Cards to send to userTotalLbl Method
        String userCard3 = userHand2Card3.getText();
        String userCard4 = userHand3Card4.getText();
        userTotalLbl.setText(userTotalCards(userCard1, userCard2, userCard3, userCard4));
        String com1 = comHand1Card1.getText();
        String com2 = comCardStorage2.getText();
        String com3 = comCardStorage3.getText(); //Get Values from Cards to send to comTotalLbl Method
        String com4 = comCardStorage4.getText();
        comTotalLbl.setText(comTotal(com1, com2, com3, com4));
        String userWin = userTotalLbl.getText();
        String comWin = comTotalLbl.getText();  //get totals from each player
        winOrLose(userWin, comWin);
        newGameBtn.setVisible(true); //display new game button
    }//GEN-LAST:event_standBtnActionPerformed

    private void StartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtnActionPerformed
        userCards(); //assign user cards
        comCards(); //assign dealer cards
        userHand1Card1.setVisible(true);
        userHand1Card2.setVisible(true);
        comHand1Card1.setVisible(true);
        comHand1Card2.setVisible(true);
        hit2CardsBtn.setVisible(true);
        standBtn.setVisible(true);
        hit3CardsBtn.setVisible(true);
        userTotalLbl.setVisible(true);
        comTotalLbl.setVisible(true);
        StartBtn.setVisible(false);
        userHand2Card1.setVisible(false);
        userHand2Card2.setVisible(false);
        userHand2Card3.setVisible(false);

        String com1 = comHand1Card1.getText();
        String com2 = comCardStorage2.getText();
        String com3 = comCardStorage3.getText(); //Get Values from Cards to send to comTotalLbl Method
        String com4 = comCardStorage4.getText();
        comTotal(com1, com2, com3, com4);
        if (comTotal2C < 13) { //makes com hit if they have less than 13
            comHit();
            comHand1Card1.setVisible(false);
            comHand1Card2.setVisible(false);
            comHand2Card1.setVisible(true);
            comHand2Card2.setVisible(true);
            comHand2Card3.setVisible(true);
        } else if (comTotal2C < 13) { //makes com hit again if they have less than 13
            comHitAgain();
            comHand2Card1.setVisible(false);
            comHand2Card2.setVisible(false);
            comHand2Card3.setVisible(false);
            comHand3Card1.setVisible(true);
            comHand3Card2.setVisible(true);
            comHand3Card3.setVisible(true);
            comHand3Card4.setVisible(true);
        } else if (comTotal2C > 21) {
            dealerBustLbl.setText("Dealer Busted");
        }
    }//GEN-LAST:event_StartBtnActionPerformed

    private void hit3CardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hit3CardsBtnActionPerformed
        String Card1 = userHand2Card1.getText();
        String Card2 = userHand2Card2.getText();//get card values
        String Card3 = userHand2Card3.getText();
        userHand3Card1.setText(Card1);
        userHand3Card2.setText(Card2); //move card values
        userHand3Card3.setText(Card3);
        userHitAgain(); //add new card value
        NoMoreLbl.setVisible(true);
        hit3CardsBtn.setVisible(false);
        hit2CardsBtn.setVisible(false);
        userHand2Card1.setVisible(false); //hide old cards
        userHand2Card2.setVisible(false);
        userHand2Card3.setVisible(false);
        userHand1Card1.setVisible(false);
        userHand1Card2.setVisible(false);
        userHand3Card4.setVisible(true);
        userHand3Card1.setVisible(true);
        userHand3Card2.setVisible(true); //show new cards
        userHand3Card3.setVisible(true);
    }//GEN-LAST:event_hit3CardsBtnActionPerformed

    private void newGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameBtnActionPerformed
        this.setVisible(false); //reset game
        new mainMenuFrame().setVisible(true);
    }//GEN-LAST:event_newGameBtnActionPerformed

    public void userCards() {
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            userHand1Card1.setText(cards[0]);
        }
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            userHand1Card2.setText(cards[0]);
        }
    }

    public void comCards() {
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            comHand1Card1.setText(cards[0]);
        }
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            comCardStorage2.setText(cards[0]);
        }
    }

    public void userHit() {
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            userHand2Card3.setText(cards[0]);
        }
    }

    public void userHitAgain() {
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            userHand3Card4.setText(cards[0]);
        }
    }

    public void comHit() {
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            comCardStorage3.setText(cards[0]);
        }
        String comFirst = comHand1Card1.getText();
        comHand2Card1.setText(comFirst);
        comHand1Card1.setVisible(true);
        comHand1Card2.setVisible(true);
        comHand2Card1.setVisible(false);
        comHand2Card2.setVisible(false);
        comHand2Card3.setVisible(false);
    }

    public void comHitAgain() {
        for (int i = 0; i < cards.length; i++) {
            int randomIndexToSwap = rand.nextInt(cards.length);
            String temp = cards[randomIndexToSwap];
            cards[randomIndexToSwap] = cards[i];
            cards[i] = temp;
            comCardStorage3.setText(cards[0]);
        }
    }

    /**
     * takes coms values and converts them an integer to add together then
     * returns the total to a string to display total
     *
     * @param v1 //value 1
     * @param v2 //value 2
     * @param v3 //value 3 if used (default 0)
     * @param v4 //value 4 if used (default 0)
     * @return com2Card
     */
    public String comTotal(String v1, String v2, String v3, String v4) {
        switch (v1) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                firstValCom = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                firstValCom = Integer.parseInt(convert);
                break;
            }
            default:
                firstValCom = Integer.parseInt(v1);
                break;
        }
        ////////////////////////////////////////////
        switch (v2) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                secValCom = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                secValCom = Integer.parseInt(convert);
                break;
            }
            default:
                secValCom = Integer.parseInt(v2);
                break;
        }
        /////////////////////////////////////////////////////
        switch (v3) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                thirdValCom = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                thirdValCom = Integer.parseInt(convert);
                break;
            }
            default:
                thirdValCom = Integer.parseInt(v3);
                break;
        }
        //////////////////////////////////////////////////////
        switch (v4) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                fourthValCom = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                fourthValCom = Integer.parseInt(convert);
                break;
            }
            default:
                fourthValCom = Integer.parseInt(v4);
                break;
        }
        comTotal2C = firstValCom + secValCom + thirdValCom + fourthValCom;
        comBlackJack = firstValCom + secValCom;

        if (comBlackJack == 21) {
            dealerBustLbl.setText("Dealer has BlackJack");
            StartBtn.setVisible(true);
        } else if (comTotal2C > 21) {
            dealerBustLbl.setText("Dealer Busted");
        }
        com2Card = Integer.toString(comTotal2C);
        return com2Card;
    }

    /**
     * takes user's values and converts them an integer to add together then
     * returns the total to a string to display total
     *
     * @param v1 //value 1
     * @param v2 //value 2
     * @param v3 //value 3 if used (default 0)
     * @param v4 //value 4 if used (default 0)
     * @return userTotal
     */
    public String userTotalCards(String v1, String v2, String v3, String v4) {
        switch (v1) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                firstValUser = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                firstValUser = Integer.parseInt(convert);
                break;
            }
            default:
                firstValUser = Integer.parseInt(v1);
                break;
        }
        ////////////////////////////////////////////
        switch (v2) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                secValUser = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                secValUser = Integer.parseInt(convert);
                break;
            }
            default:
                secValUser = Integer.parseInt(v2);
                break;
        }
        ////////////////////////////////////////////
        switch (v3) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                thirdValUser = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                thirdValUser = Integer.parseInt(convert);
                break;
            }
            default:
                thirdValUser = Integer.parseInt(v3);
                break;
        }
        ////////////////////////////////////////////
        switch (v4) {
            case "K":
            case "Q":
            case "J": {
                String convert = "10";
                fourthValUser = Integer.parseInt(convert);
                break;
            }
            case "A": {
                String convert = "11";
                fourthValUser = Integer.parseInt(convert);
                break;
            }
            default:
                fourthValUser = Integer.parseInt(v4);
                break;
        }
        userTotal2C = firstValUser + secValUser + thirdValUser + fourthValUser; //add values 
        userBlackJack = firstValUser + secValUser; //determin if blackjack not
        if (userTotal2C > 21) {
            userBustLbl.setText("Bust");
        } else if (userBlackJack == 21) {
            userBustLbl.setText("BlackJack");
        }
        userTotal = Integer.toString(userTotal2C); //convert back to String
        return userTotal;
    }

    public void winOrLose(String v1, String v2) {
        int uT = Integer.parseInt(v1); //User Total
        int cT = Integer.parseInt(v2); //Com Total
        if ((uT > cT) && (uT < 22)) {
            winOrLoseLbl.setVisible(true);
            winOrLoseLbl.setText("You Win");
        } else if ((cT >= uT) && (cT < 22)) {
            winOrLoseLbl.setText("Dealer Wins");
            winOrLoseLbl.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NoMoreLbl;
    private javax.swing.JButton StartBtn;
    private javax.swing.JLabel comCardStorage2;
    private javax.swing.JLabel comCardStorage3;
    private javax.swing.JLabel comCardStorage4;
    private javax.swing.JLabel comHand1Card1;
    private javax.swing.JLabel comHand1Card2;
    private javax.swing.JLabel comHand2Card1;
    private javax.swing.JLabel comHand2Card2;
    private javax.swing.JLabel comHand2Card3;
    private javax.swing.JLabel comHand3Card1;
    private javax.swing.JLabel comHand3Card2;
    private javax.swing.JLabel comHand3Card3;
    private javax.swing.JLabel comHand3Card4;
    private javax.swing.JLabel comTotalLbl;
    private javax.swing.JLabel dealerBustLbl;
    private javax.swing.JButton hit2CardsBtn;
    private javax.swing.JButton hit3CardsBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newGameBtn;
    private javax.swing.JButton standBtn;
    private javax.swing.JLabel userBustLbl;
    private javax.swing.JLabel userHand1Card1;
    private javax.swing.JLabel userHand1Card2;
    private javax.swing.JLabel userHand2Card1;
    private javax.swing.JLabel userHand2Card2;
    private javax.swing.JLabel userHand2Card3;
    private javax.swing.JLabel userHand3Card1;
    private javax.swing.JLabel userHand3Card2;
    private javax.swing.JLabel userHand3Card3;
    private javax.swing.JLabel userHand3Card4;
    private javax.swing.JLabel userTotalLbl;
    private javax.swing.JLabel winOrLoseLbl;
    // End of variables declaration//GEN-END:variables
}
